In [ ]:
import numpy as np
# vector array
a= np.array([1,2,3])
print(a);

[1 2 3]


In [ ]:
#matrix array 
b = np.array([[1,2,3],[4,5,6]]);
print(b);

[[1 2 3]
 [4 5 6]]


In [ ]:
#Tensor Array
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
