In [70]:
import numpy as np
# vector array
a= np.array([1,2,3])
print(a);


[1 2 3]


In [71]:
#matrix array 
b = np.array([[1,2,3],[4,5,6]]);
print(b);

[[1 2 3]
 [4 5 6]]


In [72]:
#Tensor Array
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [73]:
#dtype 
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [74]:
#np.arange
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
np.arange(1, 11,2)

array([1, 3, 5, 7, 9])

In [76]:
#with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [77]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
#linear space
np.linspace(-10,10,9)

array([-10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,  10. ])

In [80]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
#np.random
np.random.random((3,4)  )

array([[0.44024396, 0.04967168, 0.39402566, 0.30016731],
       [0.36817457, 0.21491868, 0.83897884, 0.44833491],
       [0.8364426 , 0.27050947, 0.30903974, 0.16618401]])

In [86]:
a1 =  np.arange(10)
a2= np.arange(12, dtype=float).reshape(3,4);
a3 = np.arange(8).reshape(2,2,2)
# print(a3);
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# number of dimension (ndim)
print(a3.ndim)

3


In [99]:
#shape
a2.shape

(3, 4)

In [100]:
#size
print(a1.size)


10


In [ ]:
#itemsize  mermory  used 8byte int and float
a1.itemsize

8

In [98]:
#dtype
print(a1.dtype);
print(a2.dtype);
print(a3.dtype);

int64
float64
int64


In [101]:
#changing datatype
#astype
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [106]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [108]:
#scaler operation means opertion with only single value
#arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [110]:
#relational operator
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vertor operations
#arithmetic
a1*a2